language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: rSp/pTmD5MScCYxG9Bu9e4IoaP+vO8PGQmtRrwJmVfwE9f6JQz41VKfp+sTCjoBFf8hT4DGYj1RjM1gv/M2CGabZXsH5Udmtz0UAcU5OCPOblEWcRFLNeW0NJYU8QvSzp4t2c03b8OFTwHBcPVcsNrxQDoF6jgKDxx9qkGF2MyhI1EWG1PRh5ePfx0RpZtr7nFK5YcHbqmfCbITxes8+A4rUYADjA5O3o25KPvAomCojQAnR6iTC+ufNamhho2lwv65DrELUObUCN9FyJCcsrxppx+K7Ggo21efzC/52tlK3uuZHVxZVREXxrYSNBEMV42If25RjojHp1ITRAvoZJLjyUtVUYXz6Nvzjl+bzcfUoz+DBr14yHfxghuy4nRykCvGIJS5/Z19GQw9S41NBwKXVgPOJTduncnhS6+W7W6DdwMaiBjJq/4wAFNZ3/d6F7PdqOaozUCCHiFzYjDsfJ703P7aWrbkeZatgxLKJ1wYB3PRLmnv2FZ+PUzTKdea5cHXqlYAjel+SqRXLHnxCUbSOJQIclnyR4Uk/Z5lWNhOYWmH3eaAx1hs9gSzdUwKPuyJRJhJLNuSe1aO6qQDxuzuVMhpRZGZlhCMp2MbQL+nNMh7A1EbLO6dPWMJ2LFXZvOs1rXaMilZLIQ8elQItRShGAp/I6+WzbE8dGb/7IwI=
  app: ditties
  on:
    repo: amyspeed/Ditties-Node-Capstone
  skip_cleanup: 'true'
